project:
  type: website

  preview:
    port: 4200
    browser: false
    
  render:
    - '*.qmd'

execute: 
  freeze: auto
      
website:
  title: "Lucas A. Meyer"
  google-analytics: "G-6KTZ853BN5"
  margin-footer: subscribe.html
  twitter-card: true
  open-graph: true
  site-url: https://www.meyerperin.com
  description: "Lucas A. Meyer's blog"
  favicon: /favicon-32x32.png

  navbar:
    logo: /images/mplogo.png
    left:
      - text: "Home"
        file: index.qmd
      - text: "Reviews"
        file: reviews.qmd
      - text: "Using Quarto"
        file: using_quarto/index.qmd
      - text: "GitHub Repositories" 
        menu:
          - text: "OpenAI Vision API with the Semantic Kernel"
            href: https://github.com/lucas-a-meyer/sk-vision-py
          - text: "Pytly: Python client for the T.LY link shortener"
            href: https://github.com/lucas-a-meyer/pytly     
    right:
      - text: "{{< iconify fa6-brands threads >}}"
        href: https://threads.net/@lucas_a_meyer
      - icon: linkedin
        href: https://www.linkedin.com/in/lucasameyer      
      - icon: github
        href: https://github.com/lucas-a-meyer
      - icon: stack-overflow
        href: https://stackoverflow.com/users/1850561/lucas-a-meyer
      - text: "Contact"
        href: contact.qmd
      - about.qmd


format:
  html:
    theme: flatly
    css: styles.css
    grid:
      sidebar-width: 500px
