project:
  type: website
  output-dir: docs
  # pre-render: ./pre-render.sh
  # post-render: ./post-render.sh
  preview:
    port: 4200
    browser: false

  render:
    - '*.qmd'
    - '!staged_posts/'

website:
  title: "Lucas A. Meyer"
  google-analytics: "G-6KTZ853BN5"
  twitter-card: true
  open-graph: true
  site-url: https://www.meyerperin.com
  description: "Lucas A. Meyer's blog"
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
      showHighlights: always
  favicon: /images/data-beaker.png
  navbar:
    left:
        - text: "Home"
          file: index.qmd
        - text: "Quarto with Python"
          href: /using-quarto
    right:
      - text: "{{< iconify fa6-brands threads >}}"
        href: https://threads.net/@lucas_a_meyer
      - icon: linkedin
        href: https://www.linkedin.com/in/lucasameyer      
      - icon: github
        href: https://github.com/lucas-a-meyer
      - icon: stack-overflow
        href: https://stackoverflow.com/users/1850561/lucas-a-meyer
      - about.qmd


format:
  html:
    theme: pulse
    css: styles.css
