project:
  type: website
  output-dir: docs

website:
  title: "Lucas A. Meyer"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: cosmo
    css: styles.css



