project:
  type: website
  output-dir: docs
  pre-render: ./pre-render.sh
  post-render: ./post-render.sh
  preview:
    port: 4200
    browser: false

website:
  title: "Lucas A. Meyer"
  google-analytics: "G-6KTZ853BN5"
  twitter-card: true
  open-graph: true
  site-url: https://www.meyerperin.com
  description: "Lucas A. Meyer's blog"
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
      showHighlights: always

  body-footer: '<center><p>&nbsp;</p><font size="2">Posts on this blog are **not** sponsored. Regardless, links to products or services that might compensate have the #ad tag</font></center>'
  navbar:
    left:
        - text: "Home"
          file: index.qmd
        - text: "Using Quarto"
          href: /using-quarto
        - text: "GNNs with Python"
          href: /python-gnn
        - text: "Econometrics with Python"
          href: /econometrics-python
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/lucasameyer      
      - icon: github
        href: https://github.com/lucas-a-meyer
      - icon: twitter
        href: https://twitter.com/lucas_a_meyer
      - about.qmd

format:
  html:
    theme: pulse
    css: styles.css
