project:
  type: website
  output-dir: docs
  pre-render: ./pre-render.sh
  post-render: ./post-render.sh
  preview:
    port: 4200
    browser: false

website:
  title: "Lucas A. Meyer"
  google-analytics: "G-6KTZ853BN5"
  navbar:
    left:
        - text: "Home"
          file: index.qmd
        - text: "LinkedIn Posts"
          file: linkedin-index.qmd
        - text: "Using Quarto"
          href: /using-quarto
        - text: "GNNs with Python"
          href: /python-gnn
        - text: "Econometrics with Python"
          href: /econometrics-python
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/lucasameyer      
      - icon: github
        href: https://github.com/lucas-a-meyer
      - icon: twitter
        href: https://twitter.com/lucas_a_meyer
      - about.qmd

format:
  html:
    theme: pulse
    css: styles.css
