---
title: "Calendar"
include-in-header: _msft-clarity.html
---
## Future posts

+---------------+------------+-------------------------------------------------------------------------+
| Target date   | Platform   | Title                                                                   |
+===============+============+=========================================================================+
| 2022-06-30    | Blog       | My review of the Farmer's Dog food service                              |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-07-01    | Twitter    | My review of the Farmer's Dog food service                              |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-07-01    | LinkedIn   | My review of the Farmer's Dog food service                              |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-07-04    | Blog       | That's a good question                                                  |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-07-05    | Twitter    | That's a good question                                                  |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-07-05    | LinkedIn   | That's a good question                                                  |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-07-12    | Twitter    | What happens when a hiring manager posts a position on LinkedIn         |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-07-12    | LinkedIn   | What happens when a hiring manager posts a position on LinkedIn         |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-07-18    | Twitter    | The XY Problem                                                          |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-07-18    | LinkedIn   | The XY Problem                                                          |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-07-22    | Twitter    | I'm a hiring manager: this is why I didn't answer your LinkedIn message |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-07-22    | LinkedIn   | I'm a hiring manager: this is why I didn't answer your LinkedIn message |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-09-11    | Twitter    | Data science and 9/11                                                   |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-09-11    | LinkedIn   | Data science and 9/11                                                   |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-10-04    | LinkedIn   | Chesterton's Fence                                                      |
+---------------+------------+-------------------------------------------------------------------------+
| 2022-10-21    | Twitter    | Chesterton's Fence                                                      |
+---------------+------------+-------------------------------------------------------------------------+
-----------------------------------
Generated on 2022-06-29 07:00:09.253265
