---
title: Learning from others
author: Lucas A. Meyer
---

How much of what you do is borrowed from other people? When you realized you learned something from someone, did you tell them?

If you come from a disadvantaged background, there's a possibility that the adults around youy didn't have much to teach you, or worse, taught you a bunch of self-destructing behaviors. Of course this is not always true, and many people from disadvantaged backgrounds have a lot of support from their family. However, the ones that don't may distrust learning from other people. When they find themselves in a supportive environment, that's a serious impediment.

I had to learn to learn from other people myself. A few days ago, listening to a podcast (People I mostly admire) I realized that I haven't told these people what I learned from them. I don't think it's actually that common. But here it goes.

I borrow a lot from Ed Rice, a professor at the UW Foster School of Business. He also taught me how to think like an economist, and sent me to a bunch of algebra classes to improve my argumentation skills. Because of him, I start a lot of my sentences with "You know...". 

I recently wrote that I started focusing on just a single hotel chain because of Matt Fingerhut, but I borrowed a lot more from him. I noticed that he blocked time to do email. I do so myself. He once said that a meeting that without managers, people would have trouble communicating and coordinating. When I became a manager, I prioritized communicating and coordinating, and that was a successful strategy. Whenever people complained about a problem that involved other teams, he would ask: "do we already have an email thread with everyone that needs to know about this?". The email thread doesn't always solve things, we frequently need meetings for that, but it certainly gets things started. I still do these threads today.

Urzsula and the learnings of science

Jorge Pulido and incentives

This is not an exaustive list, it's just my first list of many. There are many people who taught me incredibly useful things that I didn't thank yet. I'll get to it.