---
author: Lucas A. Meyer
date: '2019-02-04'
include-after-body: '<center><p>&nbsp;</p><hr /><font size="2">Posts on this blog
  are **not** sponsored. Regardless, links to products or services that might compensate
  have the #ad tag</font></center>'
include-in-header: _msft-clarity.html
linkedin-posted: '2019-02-04'
title: A story about my father
twitter-posted: '2019-02-04'
---

My father passed away a few years ago. I don't even remember exactly when. I think it was in 2013 or 2014. We were not close when he died, and I don't remember ever being close. To my memory, he was mostly away since I was around 7, and he left home for good when I was 12 or 13. Not having a father made a lot of things harder in my life, which I imagine made me more capable in some respects.

<!-- 

## My original case for a two-parent household

Well, it's not necessarily a case for a *father*, but more a case for a household with two parents, no matter their genders. When I was a teenager, the only opinion I had was my mom's, right or wrong. Not having another parent in the house made it more expensive for me to validate my mother's opinions. One example was when I wanted to leave a low-income, dead-end job for another job. My mom was of the opinion that "job longevity" and loyalty were very valuable traits - that one shouldn't leave a job after a short period of time. My questionings didn't go very far. In that case I ended up not folowing my mother's opinion and changed jobs. I'm sure the change had a positive impact in my career, but I was terrified. 

-->

## What I remember about my father

There are a few things I remember about my father. 

1) I remember that once he carried me from his bed to my bed. I was about 6 and I was amazed that somebody could carry me. I don't remember being carried by anyone else after that. I think about this when I carry my kids.

2) I remember when he was supposed to give me breakfast (a task that always belonged to my mother) and that he wasn't much into it. I remember complaining about the way he was slicing the bread (and smushing it) and that it made him upset. To this day, I am careful when I'm slicing bread for my kids.

3) I remember that once he gave me a videogame for Christmas that was not what I wanted. He gave me the Intellivision game [Snafu](https://en.wikipedia.org/wiki/Snafu_(video_game)), I don't remember exactly what I wanted. He was again very upset. Thinking back, I should probably have disguised my disappointment better, but I was 7. I remember that I liked the game after playing it and profusely apologized, but he didn't accept my apologies.

## Being a good detective is not always great

My father was a philanderer. I also remember that he would go out very frequently and leave me with my mother, so I didn't see him very much. At some point, he got really attached to another woman (he would end up marrying her later) who had really dark, long hair. He must have told my mother that the relationship had ended, and a few months later, he traveled to a fishing trip with his friends. When he came back, I remember finding a long black hair when helping him unpack my suitcase. My mother and him had a huge fight about it. I was about 12 and didn't immediately understand why that hair was such a big deal.

## I still do things differently

I make many decisions in which the main goal is simply to be different from my father. I don't eat his favorite foods, for example. I'm careful when slicing bread for my kids, and I carry them around more than most dads. But I still can't control "being a good detective". Sometimes, when I find something that I shouldn't reveal, I still can't control myself. Hopefully, my kids will feel differently about me when the time comes. I'm working hard on it.