---
_attachments: attachments/
_etag: '"3803c09c-0000-0700-0000-62cdb7490000"'
_rid: y90DAIjYJsAQAAAAAAAAAA==
_self: dbs/y90DAA==/colls/y90DAIjYJsA=/docs/y90DAIjYJsAQAAAAAAAAAA==/
_ts: 1657648969
author: Lucas A. Meyer
categories:
- career
date: 2021-07-07 06:00:00
id: 30e71a422a02f276c2c339ce456e8cb3
include-in-header: _msft-clarity.html
linkedin-link: https://www.linkedin.com/feed/update/urn:li:share:6818567778430275584
linkedin-posted: 2021-07-07 06:00:00
linkedin-target-date: null
post-url: https://www.meyerperin.com/posts/2021-07-07-the-goodwill-account.html
title: The goodwill account
twitter-posted: 2021-07-07 06:00:00
twitter-target-date: null
---

One of the most helpful team-building exercises I participated in was very simple. It was called the "goodwill account".

The exercise was for each team member to write 2-3 things that your colleagues can do that *debit* their goodwill account with you, and three things that your colleagues do that *credit* their account with you. We would then share these around the team.

For me, the debits were:
- scheduling a meeting without looking at my free/busy
- scheduling a meeting with me outside of work hours and canceling it last minute
- surprising me with an urgent deliverable request

And the credits were:
- being efficient in meetings: having an agenda, pre-reads, action items
- giving me visibility of projects I might be involved in at some point in the future
- giving me feedback on how I could do things better

It was also helpful to learn about things that annoyed my colleagues that I did without realizing.

